:r .\Common\PostDeployment\01.DomainValue.sql
:r .\Common\PostDeployment\02.EntityType.sql
:r .\Common\PostDeployment\03.EntityInfo.sql
:r .\Common\PostDeployment\04.Account.sql
:r .\Common\PostDeployment\05.EntityState.sql
:r .\Common\PostDeployment\06.EntityStateTransition.sql
:r .\Common\PostDeployment\07.EntityProgress.sql
:r .\Common\PostDeployment\08.EntityOrganization.sql
:r .\Common\PostDeployment\09.Role.sql
:r .\Common\PostDeployment\10.TranslationCode.sql
:r .\Common\PostDeployment\11.Translation.sql
:r .\Common\PostDeployment\12.Template.sql
:r .\Common\PostDeployment\20.TestData.sql