CREATE TABLE [race].[Race]
(
	[Id] INT NOT NULL IDENTITY,
	[Name] NVARCHAR(128) NOT NULL,
	[StartRaceTime] DATETIME NULL,
	[DarknessBeginTime] DATETIME NULL,
	[DarknessEndTime] DATETIME NULL,
	[StartСompetitionTime] DATETIME NULL,
	[EndСompetitionTime] DATETIME NULL,
	[Weather] NVARCHAR(256),
	[RaceTypeId] INT NOT NULL,
	[PointId] INT NOT NULL,
	[SeasonId] INT NOT NULL,
	[EntityInfoId] INT NOT NULL,

	[MemberCount] INT NULL,
	[PigeonCount] INT NULL,
	[AverageDistance] FLOAT NULL,
	[TimeOfFirst] DATETIME NULL,
	[TimeOfLast] DATETIME NULL,
	[SpeedOfFirst] FLOAT NULL,
	[SpeedOfLast] FLOAT NULL,
	[DurationOfCompetition] FLOAT NULL,
	[TwentyPercent] INT NULL,
	[CockCount] INT NULL,
	[HenCount] INT NULL,
	[YoungCount] INT NULL,
	[YearlyCount] INT NULL,
	[AdultsCount] INT NULL,
	[MemberTwentyPercentAFact] INT NULL,
	[PigeonTwentyPercentAFact] INT NULL,
	[InFactAbidedPercent] FLOAT NULL,

	CONSTRAINT [PK_Race] PRIMARY KEY CLUSTERED ([Id]),
	CONSTRAINT [FK_Race_RaceTypeId] FOREIGN KEY ([RaceTypeId]) REFERENCES [dom].[DomainValue] ([Id]),
	CONSTRAINT [FK_Race_Point] FOREIGN KEY ([PointId]) REFERENCES [race].[Point] ([Id]),
	CONSTRAINT [FK_Race_Season] FOREIGN KEY ([SeasonId]) REFERENCES [race].[Season] ([Id]),
	CONSTRAINT [FK_Race_EntityInfo] FOREIGN KEY ([EntityInfoId]) REFERENCES [plt].[EntityInfo] ([Id])
)
