INSERT INTO [dom].[DomainValueType] ([Id], [NameCode], [DescriptionCode]) VALUES
(1, 279, NULL), --Gender
(2, 280, NULL), --Sex
(3, 281, NULL), --Language
(4, 282, NULL), --Category
(5, 283, NULL), --MemberType
(6, 284, NULL), --SeasonType
(7, 285, NULL)  --RaceType

INSERT INTO [dom].[DomainValue] ([Id], [NameCode], [DescriptionCode], [Code], [Icon], [DomainValueTypeId]) VALUES
--Gender
(1,  8,   NULL, 'M',  NULL, 1),
(2,  9,   NULL, 'F',  NULL, 1),
(3,  10,  NULL, 'U',  NULL, 1),
--Sex
(4,  15,  NULL, NULL, NULL, 2),
(5,  16,  NULL, NULL, NULL, 2),
(6,  17,  NULL, NULL, NULL, 2),
--Language
(7,  11,  NULL, 'en', NULL, 3),
(8,  12,  NULL, 'ua', NULL, 3),
--Category
(9,  417, 418, 'A', NULL, 4),
(10, 419, 420, 'B', NULL, 4),
(11, 421, 422, 'C', NULL, 4),
(12, 423, 424, 'D', NULL, 4),
(24, 425, 426, 'E', NULL, 4),
(25, 427, 428, 'F', NULL, 4),
(26, 429, 430, 'G', NULL, 4),
(27, 431, 432, 'H', NULL, 4),
--MemberType
(13, 22, NULL, NULL, NULL, 5),
(14, 23, NULL, NULL, NULL, 5),
(15, 24, NULL, NULL, NULL, 5),
(16, 25, NULL, NULL, NULL, 5),
(17, 26, NULL, NULL, NULL, 5),
(18, 27, NULL, NULL, NULL, 5),
(19, 28, NULL, NULL, NULL, 5),
--SeasonType
(20, 18, NULL, NULL, NULL, 6), --Adults
(21, 19, NULL, NULL, NULL, 6), --Youth
--RaceType
(22, 20, NULL, NULL, NULL, 7), --Single
(23, 21, NULL, NULL, NULL, 7)  --Common

INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (1, 'AF', 40, '+93', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (2, 'AL', 41, '+355', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (3, 'DZ', 42, '+213', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (4, 'AS', 43, '+1 684', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (5, 'AD', 44, '+376', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (6, 'AO', 45, '+244', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (7, 'AI', 46, '+1 264', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (8, 'AQ', 47, '+672', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (9, 'AG', 48, '+1 268', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (10, 'AR', 49, '+54', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (11, 'AM', 50, '+374', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (12, 'AW', 51, '+297', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (13, 'AU', 52, '+61', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (14, 'AT', 53, '+43', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (15, 'AZ', 54, '+994', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (16, 'BS', 55, '+1 242', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (17, 'BH', 56, '+973', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (18, 'BD', 57, '+880', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (19, 'BB', 58, '+1 246', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (20, 'BY', 59, '+375', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (21, 'BE', 60, '+32', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (22, 'BZ', 61, '+501', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (23, 'BJ', 62, '+229', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (24, 'BM', 63, '+1 441', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (25, 'BT', 64, '+975', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (26, 'BO', 65, '+591', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (27, 'BA', 66, '+387', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (28, 'BW', 67, '+267', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (29, 'BR', 68, '+55', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (30, 'VG', 69, '+1 284', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (31, 'BN', 70, '+673', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (32, 'BG', 71, '+359', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (33, 'BF', 72, '+226', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (34, 'MM', 73, '+95', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (35, 'BI', 74, '+257', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (36, 'KH', 75, '+855', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (37, 'CM', 76, '+237', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (38, 'CA', 77, '+1', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (39, 'CV', 78, '+238', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (40, 'KY', 79, '+1 345', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (41, 'CF', 80, '+236', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (42, 'TD', 81, '+235', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (43, 'CL', 82, '+56', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (44, 'CN', 83, '+86', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (45, 'CX', 84, '+61', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (46, 'CC', 85, '+61', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (47, 'CO', 86, '+57', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (48, 'KM', 87, '+269', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (49, 'CK', 88, '+682', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (50, 'CR', 89, '+506', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (51, 'HR', 90, '+385', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (52, 'CU', 91, '+53', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (53, 'CY', 92, '+357', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (54, 'CZ', 93, '+420', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (55, 'CD', 94, '+243', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (56, 'DK', 95, '+45', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (57, 'DJ', 96, '+253', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (58, 'DM', 97, '+1 767', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (59, 'DO', 98, '+1 809', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (60, 'EC', 99, '+593', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (61, 'EG', 100, '+20', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (62, 'SV', 101, '+503', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (63, 'GQ', 102, '+240', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (64, 'ER', 103, '+291', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (65, 'EE', 104, '+372', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (66, 'ET', 105, '+251', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (67, 'FK', 106, '+500', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (68, 'FO', 107, '+298', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (69, 'FJ', 108, '+679', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (70, 'FI', 109, '+358', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (71, 'FR', 110, '+33', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (72, 'PF', 111, '+689', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (73, 'GA', 112, '+241', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (74, 'GM', 113, '+220', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (75, 'GE', 114, '+995', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (76, 'DE', 115, '+49', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (77, 'GH', 116, '+233', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (78, 'GI', 117, '+350', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (79, 'GR', 118, '+30', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (80, 'GL', 119, '+299', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (81, 'GD', 120, '+1 473', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (82, 'GU', 121, '+1 671', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (83, 'GT', 122, '+502', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (84, 'GN', 123, '+224', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (85, 'GW', 124, '+245', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (86, 'GY', 125, '+592', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (87, 'HT', 126, '+509', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (88, 'VA', 127, '+39', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (89, 'HN', 128, '+504', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (90, 'HK', 129, '+852', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (91, 'HU', 130, '+36', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (92, 'IS', 131, '+354', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (93, 'IN', 132, '+91', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (94, 'ID', 133, '+62', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (95, 'IR', 134, '+98', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (96, 'IQ', 135, '+964', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (97, 'IE', 136, '+353', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (98, 'IM', 137, '+44', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (99, 'IL', 138, '+972', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (100, 'IT', 139, '+39', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (101, 'CI', 140, '+225', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (102, 'JM', 141, '+1 876', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (103, 'JP', 142, '+81', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (104, 'JO', 143, '+962', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (105, 'KZ', 144, '+7', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (106, 'KE', 145, '+254', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (107, 'KI', 146, '+686', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (108, 'KW', 147, '+965', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (109, 'KG', 148, '+996', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (110, 'LA', 149, '+856', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (111, 'LV', 150, '+371', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (112, 'LB', 151, '+961', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (113, 'LS', 152, '+266', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (114, 'LR', 153, '+231', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (115, 'LY', 154, '+218', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (116, 'LI', 155, '+423', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (117, 'LT', 156, '+370', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (118, 'LU', 157, '+352', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (119, 'MO', 158, '+853', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (120, 'MK', 159, '+389', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (121, 'MG', 160, '+261', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (122, 'MW', 161, '+265', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (123, 'MY', 162, '+60', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (124, 'MV', 163, '+960', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (125, 'ML', 164, '+223', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (126, 'MT', 165, '+356', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (127, 'MH', 166, '+692', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (128, 'MR', 167, '+222', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (129, 'MU', 168, '+230', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (130, 'YT', 169, '+262', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (131, 'MX', 170, '+52', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (132, 'FM', 171, '+691', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (133, 'MD', 172, '+373', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (134, 'MC', 173, '+377', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (135, 'MN', 174, '+976', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (136, 'ME', 175, '+382', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (137, 'MS', 176, '+1 664', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (138, 'MA', 177, '+212', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (139, 'MZ', 178, '+258', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (140, 'NA', 179, '+264', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (141, 'NR', 180, '+674', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (142, 'NP', 181, '+977', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (143, 'NL', 182, '+31', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (144, 'AN', 183, '+599', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (145, 'NC', 184, '+687', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (146, 'NZ', 185, '+64', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (147, 'NI', 186, '+505', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (148, 'NE', 187, '+227', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (149, 'NG', 188, '+234', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (150, 'NU', 189, '+683', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (151, 'KP', 190, '+850', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (152, 'MP', 191, '+1 670', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (153, 'NO', 192, '+47', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (154, 'OM', 193, '+968', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (155, 'PK', 194, '+92', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (156, 'PW', 195, '+680', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (157, 'PA', 196, '+507', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (158, 'PG', 197, '+675', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (159, 'PY', 198, '+595', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (160, 'PE', 199, '+51', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (161, 'PH', 200, '+63', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (162, 'PN', 201, '+870', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (163, 'PL', 202, '+48', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (164, 'PT', 203, '+351', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (165, 'PR', 204, '+1', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (166, 'QA', 205, '+974', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (167, 'CG', 206, '+242', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (168, 'RO', 207, '+40', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (169, 'RU', 208, '+7', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (170, 'RW', 209, '+250', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (171, 'BL', 210, '+590', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (172, 'SH', 211, '+290', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (173, 'KN', 212, '+1 869', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (174, 'LC', 213, '+1 758', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (175, 'MF', 214, '+1 599', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (176, 'PM', 215, '+508', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (177, 'VC', 216, '+1 784', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (178, 'WS', 217, '+685', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (179, 'SM', 218, '+378', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (180, 'ST', 219, '+239', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (181, 'SA', 220, '+966', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (182, 'SN', 221, '+221', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (183, 'RS', 222, '+381', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (184, 'SC', 223, '+248', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (185, 'SL', 224, '+232', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (186, 'SG', 225, '+65', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (187, 'SK', 226, '+421', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (188, 'SI', 227, '+386', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (189, 'SB', 228, '+677', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (190, 'SO', 229, '+252', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (191, 'ZA', 230, '+27', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (192, 'KR', 231, '+82', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (193, 'ES', 232, '+34', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (194, 'LK', 233, '+94', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (195, 'SD', 234, '+249', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (196, 'SR', 235, '+597', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (197, 'SZ', 236, '+268', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (198, 'SE', 237, '+46', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (199, 'CH', 238, '+41', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (200, 'SY', 239, '+963', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (201, 'TW', 240, '+886', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (202, 'TJ', 241, '+992', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (203, 'TZ', 242, '+255', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (204, 'TH', 243, '+66', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (205, 'TL', 244, '+670', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (206, 'TG', 245, '+228', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (207, 'TK', 246, '+690', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (208, 'TO', 247, '+676', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (209, 'TT', 248, '+1 868', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (210, 'TN', 249, '+216', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (211, 'TR', 250, '+90', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (212, 'TM', 251, '+993', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (213, 'TC', 252, '+1 649', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (214, 'TV', 253, '+688', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (215, 'UG', 254, '+256', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (216, 'UA', 255, '+380', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (217, 'AE', 256, '+971', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (218, 'GB', 257, '+44', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (219, 'US', 258, '+1', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (220, 'UY', 259, '+598', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (221, 'VI', 260, '+1 340', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (222, 'UZ', 261, '+998', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (223, 'VU', 262, '+678', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (224, 'VE', 263, '+58', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (225, 'VN', 264, '+84', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (226, 'WF', 265, '+681', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (227, 'YE', 266, '+967', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (228, 'ZM', 267, '+260', NULL)
INSERT INTO [dom].[Country] ([Id], [Code], [NameCode], [PhoneCode], [Icon]) VALUES (229, 'ZW', 268, '+263', NULL)
